import { useEffect, useState } from "react";
import QRCode from "qrcode";

interface Props {
  url: string;
  size?: number;
}

// Renders an inline SVG QR code. Re-renders only when `url` changes.
export function QrCode({ url, size = 220 }: Props) {
  const [svg, setSvg] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    QRCode.toString(url, { type: "svg", margin: 1, width: size })
      .then((s) => {
        if (!cancelled) setSvg(s);
      })
      .catch((e) => console.warn("[qr] failed", e));
    return () => {
      cancelled = true;
    };
  }, [url, size]);

  return (
    <div
      className="bg-white p-2 rounded inline-block"
      style={{ width: size + 16, height: size + 16 }}
      // SVG generated by trusted lib (no user content) — safe.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
